### ISSUE TITLE
Resume uploads after close the app

### ISSUE THREAD

**Issue by pablogeek** [aws/aws-sdk-ios#154]
I was working on amazon sdk v1 and in a multipart upload, is resuming properly even if You close the app. Now I've integrated the sdk v2 and the uploads always restart from 0% even I have uploaded more than 5mb. 

Is here any solution for this? Thanks

**Comment by yosuke-matsuda** [comment]
Can you share a code snippet and steps to reproduce the issue? Also, please let us know what version of the SDK you are using. Thanks.

**Comment by pablogeek** [comment]
Hi, Thanks for your response.

This is my code for upload a file.

```

CustomCredentialsProvider *credentialsProvider = [CustomCredentialsProvider credentialsWithAccessKey:[video amazonAccessKey] secretKey:[video amazonSecretKey] sessionKey:[video amazonTokenTemporary]];
                    
AWSServiceConfiguration *configuration = [AWSServiceConfiguration configurationWithRegion:[self.delegate amazonV2EndPointForVideo:video] credentialsProvider:credentialsProvider];
                    
                    
                    
AWSS3TransferManager *transferManager = [[AWSS3TransferManager alloc] initWithConfiguration:configuration
                                                                                             identifier:@"identifier"];
AWSS3TransferManagerUploadRequest *uploadRequest = [AWSS3TransferManagerUploadRequest new];
                    
                    uploadRequest.bucket = video.amazonBucket;
                    uploadRequest.key = video.uploadKey;
                    uploadRequest.contentLength = [NSNumber numberWithLongLong: [[[NSFileManager defaultManager] attributesOfItemAtPath:video.localFilePath error:nil] fileSize]];
                    uploadRequest.body = [NSURL fileURLWithPath:video.localFilePath];

                    uploadRequest.uploadProgress = video.progressBlock;

[[transferManager upload:uploadRequest] continueWithBlock:^id(BFTask *task) {

         return nil;
}];

```
This is the class CustomCredentialsProvider. I'm using this class for add the temporaryToken:

CustomCredentialsProvider.h:

```
@interface CustomCredentialsProvider : NSObject<AWSCredentialsProvider>
@property (nonatomic, readonly) NSString *accessKey;
@property (nonatomic, readonly) NSString *secretKey;
@property (nonatomic, readonly) NSString *sessionKey;

+ (instancetype)credentialsWithAccessKey:(NSString *)accessKey
                               secretKey:(NSString *)secretKey sessionKey:(NSString*)sessionKey;
- (instancetype)initWithAccessKey:(NSString *)accessKey
                        secretKey:(NSString *)secretKey sessionKey:(NSString*)sessionKey;
@end
```

CustomCredentialsProvider.m

```
#import "CustomCredentialsProvider.h"

@implementation CustomCredentialsProvider



+ (instancetype)credentialsWithAccessKey:(NSString *)accessKey
                               secretKey:(NSString *)secretKey sessionKey:(NSString*)sessionKey
{
    CustomCredentialsProvider *credentials = [[CustomCredentialsProvider alloc]initWithAccessKey:accessKey secretKey:secretKey sessionKey:sessionKey];
    return credentials;
    
}

- (instancetype)initWithAccessKey:(NSString *)accessKey
                        secretKey:(NSString *)secretKey sessionKey:(NSString*)sessionKey
{
    if (self = [super init]) {
        _accessKey = accessKey;
        _secretKey = secretKey;
        _sessionKey = sessionKey;
    }
    return self;
}



@end
```


Thanks for your help @yosuke-matsuda

**Comment by yosuke-matsuda** [comment]
Thank you. We will take a look and see if we can reproduce the issue.

As a separate note, you may want to rewrite `CustomCredentialsProvider`. The issue with the current implementation is that the session key does expire, and when it happens, all subsequent calls using the credentials provider fail.

Take a look at the implementations of `AWSWebIdentityCredentialsProvider` and `AWSCognitoCredentialsProvider` as examples. Your credentials provider should:
    * Retrieve the access key, secret key, and session key from your server.
    * Persist them locally until they expire.
    * Return the credentials when requested.
    * Re-retrieve them from your server if they are expired.
    * Calling `- refresh` also should initiate the credentials refreshing process.

I encourage you to take a look at [Amazon Cognito Identity](http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-auth.html). With Amazon Cognito, you can create unique end user identifiers for accessing AWS cloud services by using public login providers such as Amazon, Facebook, Google, and any OpenID Connect compatible provider, or by using your own user identity system. It covers many of Token Vending Machine use cases, and it is easier to use and manage than writing your own.

**Comment by pablogeek** [comment]
Thanks. The credentials are provided by a server. The server won't provide me an expired token.

Thanks

**Comment by pablogeek** [comment]
I've test this persisting until they expire and is not working too. The strange thing is in V1 is working properly.

**Comment by pablogeek** [comment]
@yosuke-matsuda Do You know something about this? thanks for your help ;). I have been trying to do this but I can't.
I don't know what I'm doing bad or if it is a bug.

Thanks!

**Comment by yosuke-matsuda** [comment]
The current version of the S3 Transfer Manager requires the same instance of the upload request for resuming it, and the progress is not recorded on disk. That is why you are not able to resume upload requests after an app termination. We will address the issue in the future version of the SDK update. Thanks.

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.1.0 to address the issue. You need to use `- resumeAll:` to resume the pending transfer. Please let us know if it resolves the issue. Thanks,

**Comment by pablogeek** [comment]
I can't test this because I'm getting another error at this line of code https://github.com/aws/aws-sdk-ios/blob/master/S3/AWSS3TransferManager.m#L389

I'm uploading in the same way than before, I didn't change anything. File  less than 5mb upload fine. But when the file is bigger than 5mb, cause this error

https://github.com/aws/aws-sdk-ios/blob/master/S3/AWSS3TransferManager.m#L389
@yosuke-matsuda

**Comment by yosuke-matsuda** [comment]
The code snippet seems outdated. Can you share the latest code snippet so that we can try to reproduce the issue? Please make sure it does not have compiler warnings. Thanks,

**Comment by pablogeek** [comment]
the last code is this:

```
CustomCredentialsProvider *credentialsProvider = [CustomCredentialsProvider credentialsWithAccessKey:[video amazonAccessKey] secretKey:[video amazonSecretKey] sessionKey:[video amazonTokenTemporary]];

AWSServiceConfiguration *configuration = [AWSServiceConfiguration configurationWithRegion:[self.delegate amazonV2EndPointForVideo:video] credentialsProvider:credentialsProvider];

AWSS3TransferManager *transferManager = [[AWSS3TransferManager alloc] initWithConfiguration:configuration
                                                                                             identifier:@"identifier"];
AWSS3TransferManagerUploadRequest *uploadRequest = [AWSS3TransferManagerUploadRequest new];
                    
                    
                    
uploadRequest.body = [NSURL fileURLWithPath:video.localFilePath];
uploadRequest.key = video.uploadKey;
uploadRequest.bucket = video.amazonBucket;

uploadRequest.uploadProgress = video.progressBlock;


[[transferManager upload:uploadRequest] continueWithBlock:^id(BFTask *task) {
                        
                        switch (task.error.code) {
                            case AWSS3TransferManagerErrorCancelled:
                            case AWSS3TransferManagerErrorPaused:
                                break;
                        }
                        if (task.error) {
                            dispatch_async(dispatch_get_main_queue(), ^{
                                
                            });
                        }else{
                            dispatch_async(dispatch_get_main_queue(), ^{
                                
                            });
                        }
                        if (task.exception) {
                            NSLog(@"transferOperation.exception: %@",task.exception);
                        }
                        
                        return nil;
                    }];

```
And CustomCredentialsProvider.m

```
#import "CustomCredentialsProvider.h"

@implementation CustomCredentialsProvider



+ (instancetype)credentialsWithAccessKey:(NSString *)accessKey
                               secretKey:(NSString *)secretKey sessionKey:(NSString*)sessionKey
{
    CustomCredentialsProvider *credentials = [[CustomCredentialsProvider alloc]initWithAccessKey:accessKey secretKey:secretKey sessionKey:sessionKey];
    return credentials;
    
}

- (instancetype)initWithAccessKey:(NSString *)accessKey
                        secretKey:(NSString *)secretKey sessionKey:(NSString*)sessionKey
{
    if (self = [super init]) {
        _accessKey = accessKey;
        _secretKey = secretKey;
        _sessionKey = sessionKey;
    }
    return self;
}

```

**Comment by yosuke-matsuda** [comment]
I believe the above code snippet has compiler warnings with the last version of the SDK. Also, you should update `CustomCredentialsProvider` as described above. You can try our [`S3TransferManager-Sample`](https://github.com/awslabs/aws-sdk-ios-samples) to test it as well.

**Comment by yosuke-matsuda** [comment]
Assuming the issue has been resolved. If you continue to experience the problem, please feel free to update the thread.

**Comment by pablogeek** [comment]
Hello @yosuke-matsuda I'm using the last SDK 2.1.1 and is still happening the issue.

I'm using the new method to create the S3TransferManager 

```
[AWSS3TransferManager registerS3TransferManagerWithConfiguration:configuration forKey:video.uploadKey];
```

and uploading with this method

```
[[AWSS3TransferManager S3TransferManagerForKey:video.uploadKey] upload:uploadRequest] continueWithBlock:^id(BFTask *task) {
```

I start to upload and close the app manually when the upload has reached more than 10mb.
Then, I initialise the app again, the upload starts from 0mb.

This is working in v1 sdk.

**Comment by yyzhu** [comment]
Hi @pablogeek , when you closed the app manually and launch app again, may I know how did you perform the resuming? could you provide a code snippet for the resuming logic?

Also, please remind that creating another `AWSS3TransferManagerUploadRequest` with same parameters (i.e. run the uploading code again) will not resume the previous uploading tasks. You need to call `- resumeAll` instead.

**Comment by pablogeek** [comment]
Hello @yyzhu 

When I launch the app again, I'm doing exactly the same, I'm not calling resumeAll.

How Can I call resumeAll?

after or before this:
```
[[AWSS3TransferManager S3TransferManagerForKey:video.uploadKey] upload:uploadRequest] continueWithBlock:^id(BFTask *task) {
```
If register an S3TransferManager with this code : 
```
registerS3TransferManagerWithConfiguration
```
is still in the app when I launch the second time the app?

**Comment by pablogeek** [comment]
Anyway,  I'm using now resumeAll, but the problem is each session of the app has a different path of the directory. I've got an error in the sdk

Error Domain=NSCocoaErrorDomain Code=260 "The operation couldn’t be completed. (Cocoa error 260.)" UserInfo=0x15855f20 {NSFilePath=/var/mobile/Containers/Data/Application/9C22B138-B472-4DA0-8888-7FC8299D7B61/Documents/C7D1DF9C-87E0-4411-B9F6-3802771BF960.m4v, NSUnderlyingError=0x1589eb50 "The operation couldn’t be completed. No such file or directory"}

The problem here is you are not getting to the current Documents path, because in each launch of the app this change since iOS8. If I print the current one is : 

CF7D2CAE641D/Documents
2015-06-04 09:11:21.389 BETA: IrisConnect[2017:665363] Documents path /var/mobile/Containers/Data/Application/4787E7E2-834D-4BB7-970D-CF7D2CAE641D/Documents

As You see after /Application/(id), could be changed by the operative system. Then the sdk is saving the last path.

**Comment by pablogeek** [comment]
@yosuke-matsuda @yyzhu Have You taken a look to this?

**Comment by pablogeek** [comment]
@yosuke-matsuda @yyzhu Hello, I just want to know if this is going to be fixed. Thanks.

**Comment by pablogeek** [comment]
@yosuke-matsuda @yyzhu Hello again, for your understanding, if I patch the SDK and write this 
```
- (BFTask *)upload:(AWSS3TransferManagerUploadRequest *)uploadRequest
          cacheKey:(NSString *)cacheKey {
    
    NSString *Original = uploadRequest.body.absoluteString;
    NSRange range = [Original rangeOfString:@"/" options:NSBackwardsSearch];
    if(range.location != NSNotFound)
    {
        NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
        NSString *basePath = ([paths count] > 0) ? [paths objectAtIndex:0] : nil;
        NSString *result = [Original substringWithRange:NSMakeRange(range.location, Original.length-range.location)];
        
        uploadRequest.body = [NSURL fileURLWithPath:[NSString stringWithFormat:@"%@%@", basePath, result]];
    }

```

is working because your sdk is getting from cache the last url of Documents directory. But When You restart the app, this url always change.

Another thing apart from this, is you are not able to set the uploadProgress block after restartAll.

**Comment by yosuke-matsuda** [comment]
The simulator does frequently change the path; however, is it an issue on the actual device?

`- resumeAll:` take a block. In the block, you can reassign a progress feedback block to the request object again.

**Comment by pablogeek** [comment]
@yosuke-matsuda I'm testing with real iphone6, ipad mini and ipod 5th gen. 

This is a technical note from Apple. https://developer.apple.com/library/ios/technotes/tn2406/_index.html

**Comment by yosuke-matsuda** [comment]
The technical note does not seem to be related to this particular issue. However, I agree that it is not a good idea to persist the documentation directory path to the disk. We will see how this should be properly handled.

**Comment by pablogeek** [comment]
@yosuke-matsuda This is related with the issue because if the amazon sdk found the file, is resuming correctly. In all of my devices each time is different directory.

**Comment by pablogeek** [comment]
@yosuke-matsuda This is not closed, still not working properly. As I said, you are saving the whole absolute url, document directory is changing every time you start the app.

**Comment by tettoffensive** [comment]
@pablogeek thanks so much for you patch! I know they are phasing this out. but this was driving me nuts.

**Comment by pablogeek** [comment]
@yosuke-matsuda Can you please apply the patch I wrote to make it work. It is not resuming a multipart upload when you close the app and run it again.

**Comment by pablogeek** [comment]
@tettoffensive I think my patch is not working anymore. Did you solve this?

**Comment by tettoffensive** [comment]
@pablogeek I had it working but that was 2 years and several apps ago. I don't know if it still works.

**Comment by ankitkhatri77** [comment]
I am using latest SDK com.amazonaws:aws-android-sdk-s3:2.6.+ and com.amazonaws:aws-android-sdk-cognito:2.6.+.

I am uploading file using TransferUtility.
I am uploading file which is 1.01 GB.after uploading 40 MB i pause upload.than after 1 min i start resume but uploading is not start with 40 MB.it start with random number which is 30 MB or 31,35,25.

What is solution for this issue.how can i handle this issue?

Please find below Code which i have done

private void beginUpload(String filePath) {
        if (filePath == null) {
            Toast.makeText(this, "Could not find the filepath of the selected file",
                    Toast.LENGTH_LONG).show();
            return;
        }
        File file = new File(filePath);
        observer = transferUtility.upload(Constants.BUCKET_NAME, file.getName(),
                file);
        observerId = observer.getId();
        Log.e("Observer ID ", String.valueOf(observerId));
       observer.setTransferListener(new UploadListener());
    }
 btnPause.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.e("==== Paused ===","Pause");
                transferUtility.pause(observerId);
            }
        });

        btnResume.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.e("==== Resume ===","Resume");
                transferUtility.resume(observerId);
            }
        });

**Comment by rahulvyas** [comment]
I am using the latest sdk objective-c version and it doesn't work as well when I pause the upload and then resume it stuck.
