### ISSUE TITLE
Error Domain=com.amazonaws.AWSS3PresignedURLErrorDomain Code=1 "accessKey in credentialsProvider can not be nil" 

### ISSUE THREAD

**Issue by jplazcano87** [aws/aws-sdk-ios#234]
i have been using amazon s3 for ios for some months and everything was working fine, now this error is appearing every time i try to upload something to a S3 Bucket

Error Domain=com.amazonaws.AWSS3PresignedURLErrorDomain Code=1 "accessKey in credentialsProvider can not be nil" 

i have the same cognito key in an android app and is working fine, also the ios app was working until today, i go back to a previous commit and still no luck

the only thing different is the version "Using AWSCore (2.2.4)
Using AWSS3 (2.2.4)" 

this is so frustrating i haven't changed anything in my code and now the upload are broken

**Comment by Siriss** [comment]
I have the same problem. My app is hosed and needs to be released in two weeks.

**Comment by yyzhu** [comment]
@jplazcano87  @Siriss 
I can confirm it is a bug in AWSS3PresignedURL. It happens when S3PresignedURL is invoked while the Cognito credentialProvider has not been refreshed at least once. (It will refresh itself automatically whenever there is AWS HTTP Request going to be sent)  For now, I suggest to use an earlier version of the AWS Mobile SDK for iOS v2.2.3. We will fix this bug in our next release. 

Thanks for the reporting.

**Comment by Siriss** [comment]
It is still not working in 2.2.3.

**Comment by yyzhu** [comment]
@Siriss 

 It should work in 2.2.3, if you are installing the SDK via Cocoapods, I suggest to perform following steps:

1. close Xcode
2. delete the Podfile.lock and Pods/ folder in your project.
2. modify the version in Podfile to `'2.2.3'` from `'~> 2.2.0'` for all AWS services 
3. run `pod install` and confirm the 2.2.3 has been installed from system output.

**Comment by Siriss** [comment]
I have reinstalled Pods, cleaned my directory, and all of my code is identical. 2.2.3 does not work and I get the same error. Could it be a new Cognito change?

**Comment by yyzhu** [comment]
@Siriss We just released AWS Mobile SDK for iOS 2.2.5 which solved this bug. Could you have a try to see if it works?

Thanks

**Comment by nikkoss** [comment]
I'm still encountering "accessKey in credentialsProvider can not be nil" error in SDK 2.2.6 on iOS.

It happens if I launch multiple upload to S3 tasks simulteneously using my own identityProvider for AWSCognitoCredentialsProvider. Only one of the requests comes through. All the rest from the batch get this error.

Is there anything I can do to help you track this issue? Or is there a fix for that?

**Comment by yuzatom** [comment]
I'm also getting this on `2.2.7`. It can be reproduced by running the sample app `S3BackgroundTransferSampleObjC`. Error:
```
Error: Error Domain=com.amazonaws.AWSS3PresignedURLErrorDomain Code=1 "accessKey in credentialsProvider can not be nil" 
```

**Comment by qarl** [comment]
still seeing this bug.  seems to be only when submitting multiple uploads nearly simultaneously.  a one second delay between submissions makes the bug go away.  race condition.  not cool.

**Comment by akashrastogi1** [comment]
Am also facing same issue on v2.2.7. How to fix this issue?

Thanks
