### ISSUE TITLE
Duplicate definition of category 'FMDatabasePoolDelegate' on interface 'NSObject'

### ISSUE THREAD

**Issue by lvdaqian** [aws/aws-sdk-ios#341]
In AWSFMDBDatabasePool.h 

The category name of NSObject is still FMDatabasePoolDelegate. 

So there is a warning "Duplicate definition of category 'FMDatabasePoolDelegate' on interface 'NSObject'" when use FMDB together.

I am not sure whether it will lead a bug. But I think the best way to resolve it is to change the category name.

I am using cocoapods to  integrate the SDK. In fact, I only want to use AWSS3 framework.

**Comment by yosuke-matsuda** [comment]
We'll update it in the next release. Thanks!

**Comment by lvdaqian** [comment]
Thanks yosuke-matsuda.

what is your release plan?

**Comment by frootloops** [comment]
I have the same problem

**Comment by yosuke-matsuda** [comment]
We've released the AWS Mobile SDK for iOS 2.4.0, which addresses the issue. Thanks.

**Comment by maipalr** [comment]
issue still exists for 
 - AWSCore (2.5.6)
  - AWSS3 (2.5.6):
    - AWSCore (= 2.5.6)
