### ISSUE TITLE
Build error in master for credentials.json

### ISSUE THREAD

**Issue by vikram17000** [aws/aws-sdk-ios#657]
Hi - I want to build the AWS iOS SDK to generate the *.framework files, which I would then integrate dynamically in my project. However, when I open the AWSiOSSDKv2.xcodeproj file in Xcode and compile the same, I get a missing AWSCoreTests/Resources/credentials.json file error. How can I go about addressing this please?

I cannot use the SDK directly from the AWS website since the latter has the same only for v 2.5.5, which unfortunately has a compatibility issue with XMPPFramework (refer https://github.com/aws/aws-sdk-ios/issues/655), hence I am trying to use v2.5.3 where the AWSLogger hadn't been upgraded.

Many thanks.

**Comment by rohandubal** [comment]
If the error is specific to credentials.json, you can open the Xcode project and delete that file from AWSCoreTests/Resources/Credentials.json path so that Xcode does not complaint about it anymore.

**Comment by rohandubal** [comment]
Also, the Logging issue has been resolved with 2.5.6 so you should no longer required do this.

Thanks,
Rohan

**Comment by vikram17000** [comment]
Thanks for the credentials tip. Unfortunately, the logging issue still persists with other macros ...
