### ISSUE TITLE
Can not build 2.6.19 with Carthage. 

### ISSUE THREAD

**Issue by w0mba7** [aws/aws-sdk-ios#943]
### To help us solve your problem better, please answer the following list of questions.
I am trying to build with Carthage using the no binaries flag but it is failing.  I need to use the no binaries flag as the binaries are currently build with a different version of swift. 

* What service are you using? Cognito

* In what version of SDK are you facing the problem? 2.6.19

* Is the issue limited to Simulators / Actual Devices? All, it is in the build step for the SDK

* Can your problem be resolved if you bump to a higher version of SDK? No, this is the latest version, I can pin to the older version 2.6.13 and have it work.  ( This was the version i was on before i updated)

* Is this problem related to specific iOS version?

* How are you consuming the SDK? CocoaPods / Carthage / Prebuilt frameworks? Carthage
Carthage

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Create a Cartfile with 
github "aws/aws-sdk-ios"

Run 
carthage update --no-use-binaries

Error Messages 

Carthage Output 

```
Kyles-MacBook-Pro:carthage test kylekilgour$ carthage update --no-use-binaries
*** Fetching aws-sdk-ios
*** Checking out aws-sdk-ios at "2.6.19"
*** xcodebuild output can be found in /var/folders/_2/xtcq5t2529lfwxy2wzhd0tw80000gr/T/carthage-xcodebuild.19bgmT.log
*** Building scheme "AWSCloudWatch" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSAPIGateway" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSAutoScaling" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognitoIdentityProviderASF" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognitoIdentityProvider" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognito" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCognitoAuth" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSCore" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSDynamoDB" in AWSiOSSDKv2.xcodeproj
*** Building scheme "AWSComprehend" in AWSiOSSDKv2.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/kylekilgour/Desktop/carthage\ test/Carthage/Checkouts/aws-sdk-ios/AWSiOSSDKv2.xcodeproj -scheme AWSComprehend -configuration Release -derivedDataPath /Users/kylekilgour/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/aws-sdk-ios/2.6.19 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_2/xtcq5t2529lfwxy2wzhd0tw80000gr/T/aws-sdk-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/kylekilgour/Desktop/carthage test/Carthage/Checkouts/aws-sdk-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_2/xtcq5t2529lfwxy2wzhd0tw80000gr/T/carthage-xcodebuild.19bgmT.log

```

Last from log

```
SetMode u+w,go-w,a+rX /Users/kylekilgour/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/aws-sdk-ios/2.6.19/Build/Intermediates.noindex/ArchiveIntermediates/AWSComprehend/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSComprehendUnitTests.xctest
    cd "/Users/kylekilgour/Desktop/carthage test/Carthage/Checkouts/aws-sdk-ios"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/kylekilgour/.fastlane/bin:/Users/kylekilgour/homebrew/sbin:/Users/kylekilgour/homebrew/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
    /bin/chmod -RH u+w,go-w,a+rX /Users/kylekilgour/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/aws-sdk-ios/2.6.19/Build/Intermediates.noindex/ArchiveIntermediates/AWSComprehend/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSComprehendUnitTests.xctest

```
** ARCHIVE FAILED **

The following build commands failed:

```
CpResource AWSCoreTests/Resources/credentials.json /Users/kylekilgour/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/aws-sdk-ios/2.6.19/Build/Intermediates.noindex/ArchiveIntermediates/AWSComprehend/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSComprehendTests.xctest/credentials.json
(1 failure)
```

**Comment by kvasukib** [comment]
Thank you @w0mba7 for reporting to us. Sorry for the inconvenience caused. We fixed this issue in the latest commit in the repository, but the git tag points to the second latest commit, hence Carthage update fails. However, Carthage build succeeds and we have verified this. We will fix it with the next upcoming release.

Meanwhile there are two options:
1) Carthage build --no-skip-current
2) Download the Carthage frameworks from the releases tab.

**Comment by w0mba7** [comment]
Thanks, I saw the commit and figured something else was going, but if it just not in the release I can get around with the no-skip flag.

**Comment by w0mba7** [comment]
Sorry Reopened as the build still fails, looks like there is a missing file.  I opened up the project file and yup the credentials.json is red in the project navigator in xcode. 

error: /Users/kylekilgour/code/RxMobile_iOS/Carthage/Checkouts/aws-sdk-ios/AWSCoreTests/Resources/credentials.json: No such file or directory

**Comment by minbi** [comment]
The problem should be resolved in the 2.6.20 release
